/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *  http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include <bootutil/sign_key.h>

/*
 * Even though this is in principle a Zephyr-specific file, the
 * simulator builds it and uses it as well. Because of that, we can't
 * use Kconfig symbols for key types, and have to rely on the MCUBoot
 * symbols (which Zephyr provides via this header, and the simulator
 * provides via the compiler command line).
 */
#include <mcuboot_config/mcuboot_config.h>

#if defined(MCUBOOT_HW_KEY)
#include "low_level_otp.h"
#endif

#if !defined(MCUBOOT_HW_KEY)
#if defined(MCUBOOT_SIGN_RSA) || defined(MCUBOOT_SIGN_EC256) || defined(MCUBOOT_SIGN_ED25519)
#define HAVE_KEYS
#if defined(MCUBOOT_SIGN_RSA)
extern const unsigned char rsa_pub_key[];
extern unsigned int rsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_EC256)
extern const unsigned char ecdsa_pub_key[];
extern unsigned int ecdsa_pub_key_len;
#elif defined(MCUBOOT_SIGN_ED25519)
extern const unsigned char ed25519_pub_key[];
extern unsigned int ed25519_pub_key_len;
#endif
#endif

/*
 * NOTE: *_pub_key and *_pub_key_len are autogenerated based on the provided
 *       key file. If no key file was configured, the array and length must be
 *       provided and added to the build manually.
 */
#if defined(HAVE_KEYS)
const struct bootutil_key bootutil_keys[] = {
    {
#if defined(MCUBOOT_SIGN_RSA)
        .key = rsa_pub_key,
        .len = &rsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_EC256)
        .key = ecdsa_pub_key,
        .len = &ecdsa_pub_key_len,
#elif defined(MCUBOOT_SIGN_ED25519)
        .key = ed25519_pub_key,
        .len = &ed25519_pub_key_len,
#endif
    },
};
const int bootutil_key_cnt = 1;
#endif /* HAVE_KEYS */

#if defined(MCUBOOT_ENCRYPT_RSA) || defined(MCUBOOT_ENCRYPT_X25519) || defined(MCUBOOT_ENCRYPT_EC256)
extern const unsigned char enc_priv_key[];
extern unsigned int enc_priv_key_len;
const struct bootutil_key bootutil_enc_key = {
    .key = enc_priv_key,
    .len = &enc_priv_key_len,
};
#elif defined(MCUBOOT_ENCRYPT_KW)
#error "Encrypted images with AES-KW is not implemented yet."
#endif

#else
#if defined(CONFIG_BOOT_USE_STM32_HAL)
/* Use the STM32 OTP hal to retrieve the keys */

/* Image signing */
extern uint8_t Authentication_Public_Key_HASH[];

unsigned int pub_key_len = SHA256_LENGTH;
const int bootutil_key_cnt = 1;

struct bootutil_key bootutil_keys[] = {
  {
    .key = Authentication_Public_Key_HASH,
    .len = &pub_key_len,
  },
};

/* Image encryption */
#if defined(MCUBOOT_ENC_IMAGES)
extern uint8_t Encryption_Private_Key[];
unsigned int Encryption_Private_Key_Length = ECDSA_256_PRIV_KEY_LENGTH;

const unsigned char enc_priv_key_nite[] = {
    0x30, 0x41, 0x02, 0x01, 0x00, 0x30, 0x13, 0x06,
    0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01,
    0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03,
    0x01, 0x07, 0x04, 0x27, 0x30, 0x25, 0x02, 0x01,
    0x01, 0x04, 0x20, 0x68, 0x9e, 0x71, 0x96, 0x42,
    0x66, 0xef, 0xfd, 0xf2, 0xca, 0x83, 0xcc, 0xa0,
    0xbe, 0x73, 0x2c, 0x69, 0x07, 0x4d, 0xd6, 0x79,
    0x81, 0x29, 0x3e, 0xbc, 0xa2, 0xd1, 0xf3, 0x32,
    0xd0, 0x7c, 0xd8,
};
const unsigned int enc_key_lenght_nite = sizeof(enc_priv_key_nite);

struct bootutil_key bootutil_enc_key =
{
  .key = enc_priv_key_nite,
  .len = (unsigned int*)&enc_key_lenght_nite,
};

#endif

/**
  * @brief Retrieve the hash of the corresponding public key.
  * @param image_index Index of the image.
  * @param public_key_hash Buffer to store the key-hash in.
  * @param key_hash_size Size of the buffer
  * @return 0 on success; nonzero on failure.
  */
int boot_retrieve_public_key_hash(uint8_t image_index,
                                  uint8_t *public_key_hash,
                                  size_t *key_hash_size)
{
  int status = 0;

  memcpy(public_key_hash, Authentication_Public_Key_HASH, *key_hash_size);

  return status;
}

#endif /* CONFIG_BOOT_USE_STM32_HAL */
#endif /* !MCUBOOT_HW_KEY */